### ISSUE TITLE
Does the watch counter include native bind once which is available in angular 1.3+ ?

### ISSUE THREAD

**Issue by alanirudh** [tiagojsalmeida/angular-watchers#1]
Quick question related to watchers count. We use angular 1.4.1 in our application and we are using native bind once expressions in our views. But, what we have found is whether or not we have bind once in our views the counter doesn't change (increase/decrease), it changes when we delete the element though. We wanted to know if bind once is accounted in the logic while counting the counters?

**Comment by tiagojsalmeida** [comment]
Hi @alanirudh.
I just made a quick test and it seems to be working.

Take this MVC Todo example:
http://codepen.io/tiagojsalmeida/full/ojyEZq/

Here if you add one item it will add 5 watchers.

Now, I made the same MVC Todo example but with bindonce:
http://codepen.io/tiagojsalmeida/full/RWJQpe/

You can see now that only adds 4 watchers per item (I only added the bind once on the todo title).

P.S. To debug this you need to have the version 1.2 of Angular Watchers and choose the codepen iframe.

**Comment by alanirudh** [comment]
@tiagojsalmeida Thank you for the test links. It does update the count for the links that you have provided. Is there anything that you may know of that might be causing it not to work on my application ? Also, another thing that I have observed is the chart icon, it's visible for the links that you have provided but not on my application.

**Comment by tiagojsalmeida** [comment]
@alanirudh try re-installing the extension.
The chart icon only works on the 1.2 version of the extension and should appear if there's an angular app.
Let me know if it works.

**Comment by alanirudh** [comment]
@tiagojsalmeida It did work after re-installing and also the count is getting updated when the view has one-way/two-way binding. Thanks for your help.

**Comment by tiagojsalmeida** [comment]
Let me know if you have any other issue @alanirudh
