### ISSUE TITLE
Always shows 0 diff

### ISSUE THREAD

**Issue by JunedS** [tiagojsalmeida/angular-watchers#3]
I always see 0 diff. I have enabled $compileProvider.debugInfoEnabled(true); and           $logProvider.debugEnabled(true); but still no update of watchers. I am using angular version 1.5.8. Is there anything I am missing?

**Comment by tiagojsalmeida** [comment]
@JunedS can you please try again?
Please make sure you update and restart chrome to have the new 1.4 version.

**Comment by cwkwong** [comment]
I'm also encountering this similar issue. The watcher counter was working before. Updated and restarted Chrome, checked and confirm angular-watchers is at version 1.4 currently.

**Comment by tiagojsalmeida** [comment]
@cwkwong can you make a jsfiddle with a basic example of your code structure so I can understand better the problem?
What's your angular version?

**Comment by cwkwong** [comment]
I think I know why. The latest commit at https://github.com/tiagojsalmeida/angular-watchers/pull/4/commits/9432cb8a7c2fabb30d436fde570e983359683ad9 in the pull request does the following:

```
....(angular.element( window.document.querySelector('[ng-app]') ).scope());
```

My current app doesn't use `ng-app` directive in the html, but instead does a manual bootstrap such as described here:
http://www.c-sharpcorner.com/uploadfile/dbd951/creating-angular-app-without-using-ng-app-directive/

Somewhere in one of our app's js files, we have:

```
...
 // Start the application when ready...
    angular.element(document).ready(function() {
      angular.module('app', ['main', 'ui.router', 'scenario', 'product',
        'schedule', 'system.settings', 'xeditable', 'ngRoute',
        'users']).config(.....
...
```

Forgot to add, angular version is `1.3.16`

**Comment by vaso2** [comment]
@cwkwong thanks, confirm about ng-app - previously I've used data-ng-app and change fixed the issue

**Comment by dehim** [comment]
![image](https://cloud.githubusercontent.com/assets/9805228/19617576/6415c67e-9866-11e6-8aa9-02dd1d786341.png)
![image](https://cloud.githubusercontent.com/assets/9805228/19617537/ae0644e4-9865-11e6-8417-01f80fa6c1e9.png)

**Comment by Ishmaeel** [comment]
Sorry about [that](https://github.com/tiagojsalmeida/angular-watchers/pull/4#issuecomment-256275407). 

**@Those who had no problems before version 1.4:** Can you please try to install [my new version](https://github.com/Ishmaeel/angular-watchers/archive/4b044145dba8760e0f0a9df50a88245c5850581e.zip) as a [developer extension](https://developer.chrome.com/extensions/getstarted#unpacked) and see if it solves your issue? (Note: do not forget to remove the version from the web store first)

**Comment by cwkwong** [comment]
Thanks @Ishmaeel I've downloaded your new version it the counters are working for me. I'll continue to use/test it and report if there's any issues.

**Comment by nunofaria11** [comment]
Hi there,

We also bootstrap an angular app with requirejs and this extension stopped working for us.
Is this scheduled to be improved/reverted (https://github.com/tiagojsalmeida/angular-watchers/pull/4/commits/9432cb8a7c2fabb30d436fde570e983359683ad9)?

**Comment by Ishmaeel** [comment]
@nunofaria11: can you try [this](https://github.com/tiagojsalmeida/angular-watchers/issues/3#issuecomment-256277563) to see if it solves your issue? I'm trying to make sure this "improvement" does not break anything else before making a PR for it.

**Comment by nunofaria11** [comment]
@Ishmaeel your version seems to work and I haven't noticed any side effects

**Comment by tiagojsalmeida** [comment]
@cwkwong @vaso2 @nunofaria11 @Ishmaeel I fixed the issue and added a input on the configuration.
You can now target the bootstrapped elements like **#myApp**. Also works with classes or any other query selector.
If your bootstrapped element is wrong, it will fallback to ng-app and body elements.

Please update to version 1.5.
https://github.com/tiagojsalmeida/angular-watchers/releases/tag/v1.5
