### ISSUE TITLE
Possible count inaccuracy

### ISSUE THREAD

**Issue by chrisparton1991** [tiagojsalmeida/angular-watchers#8]
Hi there, I'm a big fan of your plugin, thanks for creating it!

Whilst investigating the performance of an Angular app, I came across your plugin and [this code snippet](https://medium.com/@kentcdodds/counting-angularjs-watchers-11c5134dc2ef#.89nt0fleg) that calculates the total number of watchers.

Your plugin and that code snippet give different results (the code snippet returns a larger amount of watchers). The difference looks to be that the code snippet takes into account `isolateScope()` watchers, where yours doesn't.

What are your thoughts on including `isolateScope` watchers in the count? Will that provide a more accurate result? The difference can be quite large in some cases. For instance, your plugin tells me a typical `ui-select` widget contains around 40 watchers, and the code snippet reports around 150.

**Update:** A page of an app I'm working to optimise is reported to have 5596 watchers by the plugin and 11375 watchers by the code snippet. Much too high either way :)

**Comment by tiagojsalmeida** [comment]
Hi @chrisparton1991 !

Makes sense and it should be simple to add the isolated scope watcher count.
I'm a bit busy at the moment but feel free to make a Pull Request with the changes - otherwise I will look into it soon.

**Comment by egm0121** [comment]
Hi @chrisparton1991 and @tiagojsalmeida , i've been investigating the  
[snippet](https://medium.com/@kentcdodds/counting-angularjs-watchers-11c5134dc2ef#.89nt0fleg), while the approach he takes in calculating the number of watchers via DOM traversal + angular.element().data().$isolateScope && .$scope should be reliable as well ,
the snippet fails to exclude already visited scopes when traversing and summing up the total watchers counter .
This is problematic as some elements don't have their own scope but inherit the closer ancestor one 
So I believe what happens is that traversing DOM element children the same scopes are potentially visited more than once .

I've slightly modified the snippet to ignore  any already visited scope , the resulting counts are equal or much more closer the the ones of the $$extension method (based purely on scope chain traversal).

see the modified version: 
https://gist.github.com/egm0121/f2f1a190567aa6fe9798c82ab393b746

**Comment by chrisparton1991** [comment]
I just ran your modifier version @egm0121. Interestingly, it gives me less watchers than `$$watchers` (5014 vs. 5770).

I've been looking around in the scopes and found the `$$watchersCount` variable. On the page I tested, the value reported by that count is the same as the value reported by this plugin. I retrieved this value using `$('body').scope().$$watchersCount`.

It's worth noting that my project uses a modifier version of [this watcher toggler directive](https://monterail.com/blog/2015/story-of-angular-watchers-toggler-directive) to reduce the number of watchers. This works fine and the plugin correctly reports the reduced watchers, but the `$$watchersCount` value isn't changed to reflect the changed watchers.

So based on this, it seems to me that the plugin is probably using the most accurate counting strategy. I'm not sure how the isolateScope watchers are being factored in, but it seems to be accurate.

Happy to close this if you guys are. But it anyone wants to do further research, be my guest :)

**Comment by egm0121** [comment]
Hi @chrisparton1991 yes I think the current count strategy used in $$watchers it's accurate, the $$watchersCount as you said, will not reflect the currently active number of watchers when using a library interfering with the core framework flow (expl. the directive linked in your comments).
Also it would be interesting to know which is the version of angular.js currently used in that specific project.

The isolate scopes are factored in because the plugin works by walking the entire angular scope tree , from the rootScope , touching every descendant scope , normal or isolated.

The difference with the isolated scope is that it doesn't prototypically inherit from parent scopes, but this doesn't affect the tree traversal, for the $$watchers perspective it's just another Scope to visit.

For reducing the number of watchers did you try the one time binding approach ? ng 1.3 + or the [bindonce](https://github.com/Pasvaz/bindonce) directive for older versions.

@tiagojsalmeida I would close the issue for now and re-open if someone investigates further.

**Comment by chrisparton1991** [comment]
Hi @egm0121, I agree with what you're saying. The red herring for me was the explicit mention of `isolateScope()` in the snippet, but I can see how the scope traversal being done by the plugin would include those (and is a more performant solution than searching each DOM element).

The project I'm working on is using Angular 1.5.8. The page has so many watchers because it's a giant form with hundreds of fields (including lots of `ui-select`s, which create dozens of watchers each). We're moving as much as we can to use one-time binding, as well as looking into other performance optimisations. Fun times ahead!

Thanks for your feedback and suggestions!

I'll close the issue, and contact the author of the code snippet to let them know that it's most likely inaccurate.
